
spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0
  output:
    ansi:
      enabled: always
management:
  security:
    enabled: false
endpoints:
  actuator:
    sensitive: false